"""gen_state Status-table row model (DEVQ-004): DERIVED recomputed, HAND verbatim.

Loaded from the script path so the test needs no `scripts` package. `_derived_values`
is monkeypatched to fixed values so the row-merging logic is tested without running
pytest-inside-pytest or touching git.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parents[1]
_SPEC = importlib.util.spec_from_file_location("gen_state", _REPO / "scripts" / "gen_state.py")
gen_state = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(gen_state)

_FIXED = {
    "adr": "ADR-001..008",
    "test": "9 passed (green)",
    "journal": "7 records",
    "branch": "feature-x (abc1234)",
}


@pytest.fixture(autouse=True)
def _fixed_derived(monkeypatch):
    monkeypatch.setattr(gen_state, "_derived_values", lambda run_tests: dict(_FIXED))


def _section(rows: str) -> str:
    return "## Status\n| Area | Status |\n|---|---|\n" + rows + "\n"


def test_hand_rows_preserved_verbatim_and_derived_updated_in_place():
    section = _section(
        "| Architecture v1.1 | FROZEN |\n"
        "| ADR register | ADR-001..003 |\n"
        "| Sprint 1 (Ledger core) | **CLOSED — GO-S1** (35 tests) |\n"
        "| Journal | 2 genesis records; verified independently |\n"
    )
    out = gen_state.rebuild_status(section, True)
    # HAND rows survive byte-for-byte.
    assert "| Architecture v1.1 | FROZEN |" in out
    assert "| Sprint 1 (Ledger core) | **CLOSED — GO-S1** (35 tests) |" in out
    # DERIVED rows are recomputed in place (label + position kept, value replaced).
    assert "| ADR register | ADR-001..008 |" in out
    assert "| ADR register | ADR-001..003 |" not in out
    assert "| Journal | 7 records |" in out
    assert "| Journal | 2 genesis records; verified independently |" not in out


def test_missing_derived_rows_appended():
    section = _section("| Architecture v1.1 | FROZEN |\n")
    out = gen_state.rebuild_status(section, True)
    assert "| Test suite | 9 passed (green) |" in out
    assert "| Git branch | feature-x (abc1234) |" in out
    # The hand row still precedes the appended derived rows.
    assert out.index("Architecture") < out.index("Test suite") < out.index("Git branch")


def test_trailing_blank_line_preserved():
    out = gen_state.rebuild_status(_section("| Architecture v1.1 | FROZEN |\n"), True)
    assert out.endswith("\n\n")  # exactly one blank line before the next heading


def test_regenerate_keeps_hand_maintained_sections():
    doc = (
        "# AI Project State\n<!-- old header -->\n\n"
        + _section("| ADR register | ADR-001..001 |\n")
        + "## Next immediate task (hand-maintained)\nDo the thing.\n\n"
        + "## Don't change without discussion (hand-maintained)\nThe contract.\n"
    )
    out = gen_state.regenerate(doc, run_tests=True)
    assert "## Next immediate task (hand-maintained)\nDo the thing." in out
    assert "## Don't change without discussion (hand-maintained)\nThe contract." in out
    assert "| ADR register | ADR-001..008 |" in out
    assert "GENERATED by scripts/gen_state.py" in out
