#!/usr/bin/env python3
"""gen_state.py — regenerate docs/handover/AI_PROJECT_STATE.md (ADR-007, v0).

ADR-007: the handover/status file is *generated*, not hand-written, so a second
source of truth cannot silently diverge from the ledger. This v0 regenerates
only the **Status** table (from the ADR file list, the current git branch, and
a test-result summary) and refreshes the generated-at header. Every other
section — including the two hand-maintained ones, "Next immediate task" and
"Don't change without discussion" — is preserved byte-for-byte. Later sprints
extend this to derive open questions and verification status from ledger
records once the store holds them.

Usage:
    python scripts/gen_state.py                 # regenerate the real file
    python scripts/gen_state.py --out PATH       # write elsewhere (dry review)
    python scripts/gen_state.py --check          # print, do not write
    python scripts/gen_state.py --no-tests       # skip running the test suite

Note (ARCH-001 / DEVQ-001): CLAUDE.md forbids the Developer modifying files
under docs/. Writing this specific generated file is the sanctioned exception
per ADR-007, but authorization is pending DEVQ-001; until then run with --out
or --check to avoid touching the tracked file.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
STATE_FILE = REPO_ROOT / "docs" / "handover" / "AI_PROJECT_STATE.md"
ADR_DIR = REPO_ROOT / "docs" / "adr"

HAND_MAINTAINED_HEADINGS = (
    "## Next immediate task (hand-maintained)",
    "## Don't change without discussion (hand-maintained)",
)


def git_branch() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip() or "unknown"
    except (subprocess.SubprocessError, OSError):
        return "unknown"


def adr_range() -> tuple[str, int]:
    nums = sorted(
        int(m.group(1))
        for p in ADR_DIR.glob("ADR-*.md")
        if (m := re.match(r"ADR-(\d+)", p.name))
    )
    if not nums:
        return "none", 0
    return f"ADR-{nums[0]:03d}..{nums[-1]:03d}", len(nums)


def test_summary(run: bool) -> tuple[str, str]:
    """Return (summary_line, status) where status is 'green' | 'RED' | 'not run'."""
    if not run:
        return "not run (--no-tests)", "not run"
    try:
        proc = subprocess.run(
            [sys.executable, "-m", "pytest", "-q", "--no-header", "-p", "no:cacheprovider"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
        )
    except (subprocess.SubprocessError, OSError) as e:
        return f"could not run pytest ({e})", "unknown"
    lines = [ln.strip() for ln in proc.stdout.splitlines() if ln.strip()]
    summary = lines[-1] if lines else "no output"
    return summary, "green" if proc.returncode == 0 else "RED"


def build_status_section(run_tests: bool) -> str:
    branch = git_branch()
    rng, count = adr_range()
    summary, status = test_summary(run_tests)

    if status == "green":
        sprint1 = "Ledger core implemented; tests green — IVF Sprint-1 Go/No-Go pending"
    elif status == "RED":
        sprint1 = "Ledger core — tests RED, see Test suite row"
    else:
        sprint1 = "Ledger core implemented (ARCH-001); IVF Sprint-1 Go/No-Go pending"

    rows = [
        ("Architecture v1.1", "FROZEN"),
        ("Implementation Blueprint v1.0", "Complete"),
        ("Verification Framework v1.0", "Complete"),
        ("Docs policy + ADR register", f"{rng} ({count} decisions)"),
        ("Repository skeleton (F:\\QRF)", "Created"),
        ("Git branch", branch),
        ("Coordination channel + CLAUDE.md", "Live (ADR-008)"),
        ("Sprint 1 (Ledger core)", sprint1),
        ("Test suite", f"{summary} ({status})"),
        ("Sprints 2–8", "Specified in Blueprint §7"),
        ("Open risks", "See Architecture Ch.13"),
    ]
    body = ["## Status", "| Area | Status |", "|---|---|"]
    body += [f"| {area} | {value} |" for area, value in rows]
    return "\n".join(body) + "\n\n"


def regenerate(text: str, run_tests: bool) -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    comment = (
        f"<!-- GENERATED by scripts/gen_state.py (ADR-007). The Status table below\n"
        f"     is regenerated; the two *hand-maintained* sections are preserved\n"
        f"     verbatim. Generated-at: {now}. Branch: {git_branch()}. -->"
    )
    # Replace the first HTML comment (the generated-at header).
    text = re.sub(r"(?s)<!--.*?-->", lambda _: comment, text, count=1)
    # Replace the Status section (up to the next '## ' heading or EOF).
    new_status = build_status_section(run_tests)
    text, n = re.subn(
        r"(?ms)^## Status\b.*?(?=^## |\Z)",
        lambda _: new_status,
        text,
        count=1,
    )
    if n != 1:
        raise SystemExit("error: could not locate a '## Status' section to regenerate")

    # Safety: the two hand-maintained sections must survive unchanged.
    for heading in HAND_MAINTAINED_HEADINGS:
        if heading not in text:
            raise SystemExit(f"error: hand-maintained section vanished: {heading!r}")
    return text


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=None, help="write to this path instead")
    ap.add_argument("--check", action="store_true", help="print to stdout, do not write")
    ap.add_argument("--no-tests", action="store_true", help="skip running the test suite")
    args = ap.parse_args(argv)

    if not STATE_FILE.exists():
        raise SystemExit(f"error: {STATE_FILE} not found")
    original = STATE_FILE.read_text(encoding="utf-8")
    regenerated = regenerate(original, run_tests=not args.no_tests)

    if args.check:
        sys.stdout.write(regenerated)
        return 0
    dest = args.out or STATE_FILE
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(regenerated, encoding="utf-8")
    print(f"wrote {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
